# Generated by Django 4.2.7 on 2023-11-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="df_agama",
            fields=[
                ("agama_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("agama", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="df_bagian",
            fields=[
                ("bagian_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bagian", models.TextField()),
                ("status_bagian", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="df_jabatan",
            fields=[
                ("jabatan_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("jabatan", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="df_kelas_kantor",
            fields=[
                (
                    "kelas_kantor_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("kelas_kantor", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="df_posisi",
            fields=[
                ("posisi_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("posisi", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="df_regional",
            fields=[
                ("regional_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("regional", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="df_status_kerja",
            fields=[
                (
                    "status_kerja_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("status_kerja", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="df_status_nikah",
            fields=[
                (
                    "status_nikah_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("status_nikah", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="df_status_pegawai",
            fields=[
                (
                    "status_pegawai_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("status_pegawai", models.TextField()),
            ],
        ),
    ]
