# Generated by Django 4.2.7 on 2023-11-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_df_kantor_delete_df_kntor"),
    ]

    operations = [
        migrations.CreateModel(
            name="df_sdm",
            fields=[
                ("nippos", models.BigIntegerField(primary_key=True, serialize=False)),
                ("nama", models.TextField()),
                ("tgl_lahir", models.TextField()),
                ("tempat_lahir", models.TextField()),
                ("total_grade", models.TextField()),
                ("suskel", models.TextField()),
                ("jenis_kelamin", models.TextField()),
                ("tgl_meninggal", models.TextField()),
                ("tgl_disumpah", models.TextField()),
                ("tgl_kerja", models.TextField()),
                ("tgl_berhenti", models.TextField()),
                ("golongan_darah", models.TextField()),
                ("alamat", models.TextField()),
                ("kota", models.TextField()),
                ("kodepos", models.TextField()),
                ("telp", models.TextField()),
                ("no_urut", models.TextField()),
                ("status", models.TextField()),
                ("passs", models.TextField()),
                ("npwp", models.TextField()),
                ("userid", models.TextField()),
                ("status_transfer", models.TextField()),
                (
                    "agama",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.df_agama"
                    ),
                ),
                (
                    "status_kerja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.df_status_kerja",
                    ),
                ),
                (
                    "status_nikah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.df_status_nikah",
                    ),
                ),
                (
                    "status_pegawai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.df_status_pegawai",
                    ),
                ),
            ],
        ),
    ]
