# Generated by Django 4.2.7 on 2023-11-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_df_sdm_kode_jiwa_df_sdm_masih_hidup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="df_kategori_durasi",
            fields=[
                (
                    "kategori_durasi_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("kategori_durasi", models.TextField()),
            ],
        ),
    ]
