# Generated by Django 4.2.7 on 2023-11-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_df_kategori_durasi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="df_sdm",
            name="kode_jiwa",
        ),
        migrations.AddField(
            model_name="df_sdm",
            name="kategori_durasi",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.df_kategori_durasi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="df_sdm",
            name="masa_kerja",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="df_sdm",
            name="masih_hidup",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
