# Generated by Django 4.2.7 on 2023-11-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_df_sdm_kode_jiwa_df_sdm_kategori_durasi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="df_sdm",
            name="tempat_lahir",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="df_sdm",
            name="tgl_berhenti",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="df_sdm",
            name="tgl_disumpah",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="df_sdm",
            name="tgl_kerja",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="df_sdm",
            name="tgl_meninggal",
            field=models.DateField(),
        ),
    ]
