# Generated by Django 4.2.7 on 2023-11-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_df_sdm_tempat_lahir_alter_df_sdm_tgl_berhenti_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="df_sdm",
            name="tempat_lahir",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="df_sdm",
            name="tgl_berhenti",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="df_sdm",
            name="tgl_disumpah",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="df_sdm",
            name="tgl_kerja",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="df_sdm",
            name="tgl_meninggal",
            field=models.TextField(),
        ),
    ]
