# Generated by Django 4.2.7 on 2023-11-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_df_sdm_tempat_lahir_alter_df_sdm_tgl_berhenti_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="df_mutasi",
            fields=[
                (
                    "mutasi_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("noskep", models.TextField()),
                ("tgl_skep", models.TextField()),
                ("tmt", models.TextField()),
                ("tj", models.TextField()),
                ("jenis_mutasi", models.TextField()),
                ("tgl_brgkt", models.TextField()),
                ("tgl_aktif", models.TextField()),
                ("status", models.TextField()),
                ("userid", models.TextField()),
                ("tgl_insert", models.TextField()),
                ("keterangan", models.TextField()),
                ("level_jabatan", models.TextField()),
                ("uid_insert", models.TextField()),
                ("wkt_update", models.TextField()),
                ("uid_update", models.TextField()),
                ("rumpun", models.TextField()),
                ("tgl_sk", models.TextField()),
                ("nomor_sk", models.TextField()),
                ("tmt_sk", models.TextField()),
                ("rank", models.TextField()),
                ("next_tmt", models.TextField()),
                ("rank_jabatan", models.TextField()),
                ("durasi_jabatan_sebelumnya", models.TextField()),
                ("masakerja_jabatan_sebelumnya", models.TextField()),
                ("rank_bagian", models.TextField()),
                ("durasi_bagian_sebelumnya", models.TextField()),
                ("masakerja_bagian_sebelumnya", models.TextField()),
                ("rank_jabatan_unitkerja", models.TextField()),
                ("durasi_jabatan_unitkerja_sebelumnya", models.TextField()),
                ("masakerja_jabatan_unitkerja_sebelumnya", models.TextField()),
                ("rank_bagian_unitkerja", models.TextField()),
                ("durasi_bagian_unitkerja_sebelumnya", models.TextField()),
                ("masakerja_bagian_unitkerja_sebelumnya", models.TextField()),
                ("tmt_jabatan", models.TextField()),
                ("tmt_bagian", models.TextField()),
                ("tmt_jabatan_unitkerja", models.TextField()),
                ("tmt_bagian_unitkerja", models.TextField()),
                ("durasi_jabatan", models.TextField()),
                ("masakerja_jabatan", models.TextField()),
                ("durasi_bagian", models.TextField()),
                ("masakerja_bagian", models.TextField()),
                ("durasi_jabatan_unitkerja", models.TextField()),
                ("masakerja_jabatan_unitkerja", models.TextField()),
                ("durasi_bagian_unitkerja", models.TextField()),
                ("masakerja_bagian_unitkerja", models.TextField()),
                (
                    "bagian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.df_bagian"
                    ),
                ),
                (
                    "jabatan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.df_jabatan"
                    ),
                ),
                (
                    "kategori_durasi_bagian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="df_mutasi_durasi_bagian",
                        to="api.df_kategori_durasi",
                    ),
                ),
                (
                    "kategori_durasi_bagian_sebelumnya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="df_mutasi_durasi_bagian_sebelumnya",
                        to="api.df_kategori_durasi",
                    ),
                ),
                (
                    "kategori_durasi_bagian_unitkerja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="df_mutasi_durasi_bagian_unitkerja",
                        to="api.df_kategori_durasi",
                    ),
                ),
                (
                    "kategori_durasi_bagian_unitkerja_sebelumnya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="df_mutasi_durasi_bagian_unitkerja_sebelumnya",
                        to="api.df_kategori_durasi",
                    ),
                ),
                (
                    "kategori_durasi_jabatan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="df_mutasi_durasi_jabatan",
                        to="api.df_kategori_durasi",
                    ),
                ),
                (
                    "kategori_durasi_jabatan_sebelumnya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="df_mutasi_durasi_jabatan_sebelumnya",
                        to="api.df_kategori_durasi",
                    ),
                ),
                (
                    "kategori_durasi_jabatan_unitkerja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="df_mutasi_durasi_jabatan_unitkerja",
                        to="api.df_kategori_durasi",
                    ),
                ),
                (
                    "kategori_durasi_jabatan_unitkerja_sebelumnya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="df_mutasi_durasi_jabatan_unitkerja_sebelumnya",
                        to="api.df_kategori_durasi",
                    ),
                ),
                (
                    "nippos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.df_sdm"
                    ),
                ),
                (
                    "nopend_asal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="df_mutasi_asal",
                        to="api.df_kantor",
                    ),
                ),
                (
                    "nopend_tujuan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="df_mutasi_tujuan",
                        to="api.df_kantor",
                    ),
                ),
                (
                    "posisi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.df_posisi"
                    ),
                ),
            ],
        ),
    ]
