# Generated by Django 4.2.7 on 2023-11-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_df_mutasi_mutasi_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="df_mutasi",
            new_name="df_mutasi_2",
        ),
    ]
